version: '3.9'

networks:
  tg-net:
   driver:
    bridge

services:
### Redis
  redis:
    image: redis:alpine
    restart: always
    networks:
    - tg-net
    ports:
    - "6379:6379"
    volumes:
      - ./data/redis:/data

### RabbitMq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    networks:
      - tg-net
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    environment:
       RABBITMQ_DEFAULT_USER: ${RabbitMqConnectionsDefaultUserName}
       RABBITMQ_DEFAULT_PASS: ${RabbitMqConnectionsDefaultPassword}

 ### MongoDb
  mongodb:
    image: mongo:latest
    restart: always
    networks:
      - tg-net
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo/:/data
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: admin
    #  MONGO_INITDB_ROOT_PASSWORD: admin

################### MyTelegram server

  ### 1.Gateway server
  gateway-server:
    image: mytelegram/mytelegram-gateway-server:${MyTelegramVersion}
    restart: always
    networks:
      - tg-net
    ports:
      - "${GatewayServerTcpPort}:20443"
      - "${GatewayServerHttpPort}:30443"
    volumes:
      - ./data/mytelegram/gateway/logs:/data/Logs
    environment:
       ConnectionStrings__Default: ${DefaultConnectionStrings}
       RabbitMQ__Connections__Default__HostName: ${RabbitMqConnectionsDefaultHostName}
       RabbitMQ__Connections__Default__Port: ${RabbitMqConnectionsDefaultPort}
       RabbitMQ__Connections__Default__UserName: ${RabbitMqConnectionsDefaultUserName}
       RabbitMQ__Connections__Default__Password: ${RabbitMqConnectionsDefaultPassword}
       Redis__Configuration: ${RedsConfiguration}
       Serilog__MinimumLevel__Default: ${DefaultLogLevel}
       App__Tcp__Ip: ${GatewayServerTcpIp}
       App__Http__Ip: ${GatewayServerHttpIp}
    depends_on:
      - rabbitmq
      - mongodb
      - redis

  ### 2.Seq server
  seq-server:
    image: mytelegram/mytelegram-seq-server:${MyTelegramVersion}
    restart: always
    networks:
      - tg-net
    #ports:
    #  - "10001:80"
    environment:
      ConnectionStrings__Default: ${DefaultConnectionStrings}
      Serilog__MinimumLevel__Default: ${DefaultLogLevel}
    volumes:
      - ./data/mytelegram/seq/logs:/data/Logs
    depends_on:
      - mongodb

  ### 3.Auth server
  auth-server:
    image: mytelegram/mytelegram-auth-server:${MyTelegramVersion}
    restart: always
    networks:
      - tg-net
    environment:
       ConnectionStrings__Default: ${DefaultConnectionStrings}
       RabbitMQ__Connections__Default__HostName: ${RabbitMqConnectionsDefaultHostName}
       RabbitMQ__Connections__Default__Port: ${RabbitMqConnectionsDefaultPort}
       RabbitMQ__Connections__Default__UserName: ${RabbitMqConnectionsDefaultUserName}
       RabbitMQ__Connections__Default__Password: ${RabbitMqConnectionsDefaultPassword}
       Redis__Configuration: ${RedsConfiguration}
       Serilog__MinimumLevel__Default: ${DefaultLogLevel}
    volumes:
      - ./data/mytelegram/auth/logs:/data/Logs
    depends_on:
      - mongodb
      - rabbitmq
      - redis

  ### 4.Session server
  session-server:
    image: mytelegram/mytelegram-session-server:${MyTelegramVersion}
    restart: always
    networks:
      - tg-net
    environment:
       ConnectionStrings__Default: ${DefaultConnectionStrings}
       RabbitMQ__Connections__Default__HostName: ${RabbitMqConnectionsDefaultHostName}
       RabbitMQ__Connections__Default__Port: ${RabbitMqConnectionsDefaultPort}
       RabbitMQ__Connections__Default__UserName: ${RabbitMqConnectionsDefaultUserName}
       RabbitMQ__Connections__Default__Password: ${RabbitMqConnectionsDefaultPassword}
       Redis__Configuration: ${RedsConfiguration}
       App__MessengerServerGrpcServiceUrl: ${MessengerServerGrpcServiceUrl}
       App__IdGeneratorGrpcServiceUrl: ${IdGeneratorGrpcServiceUrl}
       Serilog__MinimumLevel__Default: ${DefaultLogLevel}
    volumes:
      - ./data/mytelegram/session/logs:/data/Logs
    depends_on:
      - mongodb
      - rabbitmq
      - redis

  ### 5.Messenger grpc server
  messenger-grpc-server:
    image: mytelegram/mytelegram-messenger-grpc-service:${MyTelegramVersion}
    restart: always
    networks:
      - tg-net
    #ports:
    #  - "10002:80"
    environment:
       ConnectionStrings__Default: ${DefaultConnectionStrings}
       Serilog__MinimumLevel__Default: ${DefaultLogLevel}
    volumes:
      - ./data/mytelegram/messenger-grpc/logs:/data/Logs
    depends_on:
      - mongodb

  ### 6.File server
  file-server:
    image: mytelegram/mytelegram-file-server:${MyTelegramVersion}
    restart: always
    networks:
      - tg-net
    #ports:
    #  - "10003:80"
    volumes:
      - ./data/uploads:/app/uploads
      - ./data/mytelegram/file:/app/Logs
    environment:
       ConnectionStrings__Default: ${DefaultConnectionStrings} 
       RabbitMQ__Connections__Default__HostName: ${RabbitMqConnectionsDefaultHostName}
       RabbitMQ__Connections__Default__Port: ${RabbitMqConnectionsDefaultPort}
       RabbitMQ__Connections__Default__UserName: ${RabbitMqConnectionsDefaultUserName}
       RabbitMQ__Connections__Default__Password: ${RabbitMqConnectionsDefaultPassword}
       App__DcOptions__0__IpAddress: ${DcOptions0IpAddress}
       App__DcOptions__0__Port: ${DcOptions0Port}
       App__DcOptions__0__Ipv6: ${DcOptions0Ipv6}
       Serilog__MinimumLevel__Default: ${DefaultLogLevel}
    depends_on:
      - mongodb
      - rabbitmq

  ### 7.Messenger server
  messenger-server:
    image: mytelegram/mytelegram-messenger-server:${MyTelegramVersion}
    restart: always
    networks:
      - tg-net
    environment:
       ConnectionStrings__Default: ${DefaultConnectionStrings} 
       RabbitMQ__Connections__Default__HostName: ${RabbitMqConnectionsDefaultHostName}
       RabbitMQ__Connections__Default__Port: ${RabbitMqConnectionsDefaultPort}
       RabbitMQ__Connections__Default__UserName: ${RabbitMqConnectionsDefaultUserName}
       RabbitMQ__Connections__Default__Password: ${RabbitMqConnectionsDefaultPassword}
       Redis__Configuration: ${RedsConfiguration}
       App__FileServerGrpcServiceUrl: ${FileServerGrpcServiceUrl}
       App__IdGeneratorGrpcServiceUrl: ${IdGeneratorGrpcServiceUrl}
       App__DcOptions__0__IpAddress: ${DcOptions0IpAddress}
       App__DcOptions__0__Port: ${DcOptions0Port}
       App__DcOptions__0__Ipv6: ${DcOptions0Ipv6}
       Serilog__MinimumLevel__Default: ${DefaultLogLevel}
    volumes:
      - ./data/mytelegram/messenger/logs:/data/Logs
    depends_on:
      - mongodb
      - rabbitmq
      - redis
